// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.2. SEE SOURCE BELOW. !!
pragma solidity 0.8.4;

interface ISimplePriceOracle {
    event PricePosted(
        address asset,
        uint256 previousPriceMantissa,
        uint256 requestedPriceMantissa,
        uint256 newPriceMantissa
    );

    function getUnderlyingPrice(address rToken) external view returns (uint256);

    function isPriceOracle() external view returns (bool);

    function oracleData(address) external view returns (address);

    function setOracleData(address rToken, address _oracle) external;
}