// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.2. SEE SOURCE BELOW. !!
pragma solidity 0.8.4;

interface ISiloV2Facet {
    event BeanAllocation(address indexed account, uint256 beans);
    event ClaimSeason(
        address indexed account,
        address indexed token,
        uint32 season,
        uint256 amount
    );
    event ClaimSeasons(
        address indexed account,
        address indexed token,
        uint32[] seasons,
        uint256 amount
    );
    event Deposit(
        address indexed account,
        address indexed token,
        uint256 season,
        uint256 amount,
        uint256 bdv
    );
    event RemoveSeason(
        address indexed account,
        address indexed token,
        uint32 season,
        uint256 amount
    );
    event RemoveSeasons(
        address indexed account,
        address indexed token,
        uint32[] seasons,
        uint256[] amounts,
        uint256 amount
    );
    event Withdraw(
        address indexed account,
        address indexed token,
        uint32 season,
        uint256 amount
    );

    function claimTokenBySeason(address token, uint32 season) external;

    function claimTokenBySeasons(address token, uint32[] memory seasons)
    external;

    function claimTokensBySeason(SiloV2Facet.SeasonClaim[] memory claims)
    external;

    function claimTokensBySeasons(SiloV2Facet.SeasonsClaim[] memory claims)
    external;

    function deposit(address token, uint256 amount) external;

    function getDeposit(
        address account,
        address token,
        uint32 season
    ) external view returns (uint256, uint256);

    function getTotalDeposited(address token) external view returns (uint256);

    function getTotalWithdrawn(address token) external view returns (uint256);

    function getWithdrawal(
        address account,
        address token,
        uint32 season
    ) external view returns (uint256);

    function tokenSettings(address token)
    external
    view
    returns (ISiloV2FacetStorage.SiloSettings memory);

    function whitelistToken(
        address token,
        bytes4 selector,
        uint32 stalk,
        uint32 seeds
    ) external;

    function withdrawTokenBySeason(
        address token,
        uint32 season,
        uint256 amount
    ) external;

    function withdrawTokenBySeasons(
        address token,
        uint32[] memory seasons,
        uint256[] memory amounts
    ) external;

    function withdrawTokensBySeason(
        SiloV2Facet.WithdrawSeason[] memory withdraws
    ) external;

    function withdrawTokensBySeasons(
        SiloV2Facet.WithdrawSeasons[] memory withdraws
    ) external;
}

interface SiloV2Facet {
    struct SeasonClaim {
        address token;
        uint32 season;
    }

    struct SeasonsClaim {
        address token;
        uint32[] seasons;
    }

    struct WithdrawSeason {
        address token;
        uint32 season;
        uint256 amount;
    }

    struct WithdrawSeasons {
        address token;
        uint32[] seasons;
        uint256[] amounts;
    }
}

interface ISiloV2FacetStorage {
    struct SiloSettings {
        bytes4 selector;
        uint32 seeds;
        uint32 stalk;
    }
}