// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.2. SEE SOURCE BELOW. !!
pragma solidity ^0.8.4;

interface IACOWriter {
    function erc20proxy() external view returns (address);

    function weth() external view returns (address);

    function write(
        address acoToken,
        uint256 collateralAmount,
        address exchangeAddress,
        bytes memory exchangeData
    ) external payable;

    receive() external payable;
}